AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 and networking

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  # 2 subnets in different AZs
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      # Select the first AZ
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      # Select the second AZ
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true

  # Internet Gateway
  InternetGateway:
      Type: AWS::EC2::InternetGateway

  # Attach IGW to VPC
  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      # return the logical name of the IGW
      InternetGatewayId: !Ref InternetGateway

  # Route Table
  PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref VPC
  # Route to IGW
  DefaultRoute:
      Type: AWS::EC2::Route
      DependsOn: VpcGatewayAttachment
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

  # Associate subnets with route table
  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref PublicRouteTable

  SubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP inbound
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  # IAM Role for EC2
  # InstanceRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: ec2.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  # Instance Profile
  # InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref InstanceRole]
  #  Auto Scaling Group with Launch Template
  # LaunchTemplate:
  #   Type: AWS::EC2::LaunchTemplate
  #   Properties:
  #     LaunchTemplateData:
  #       ImageId: ami-08d7aabbb50c2c24e
  #       InstanceType: t3.micro
  #       IamInstanceProfile:
  #         Arn: !GetAtt InstanceProfile.Arn
  #       SecurityGroupIds:
  #         - !Ref SecurityGroup
  #       MetadataOptions:
  #         HttpTokens: required
  #       UserData:
  #         Fn::Base64: |
  #           #!/bin/bash
  #           dnf -y install httpd
  #           echo "Hello from Auto Scaling Group" > /var/www/html/index.html
  #           systemctl enable httpd
  #           systemctl start httpd

  # AutoScalingGroup:
  #   Type: AWS::AutoScaling::AutoScalingGroup
  #   Properties:
  #     VPCZoneIdentifier:
  #       - !Ref SubnetA
  #       - !Ref SubnetB
  #     MinSize: "1"
  #     MaxSize: "4"
  #     DesiredCapacity: "1"
  #     LaunchTemplate:
  #       LaunchTemplateId: !Ref LaunchTemplate
  #       Version: !GetAtt LaunchTemplate.LatestVersionNumber

  # CpuScalingPolicy:
  #   Type: AWS::AutoScaling::ScalingPolicy
  #   Properties:
  #     AutoScalingGroupName: !Ref AutoScalingGroup
  #     PolicyType: TargetTrackingScaling
  #     TargetTrackingConfiguration:
  #       PredefinedMetricSpecification:
  #         PredefinedMetricType: ASGAverageCPUUtilization
  #       TargetValue: 50

Outputs:
  VpcId:
    Value: !Ref VPC